---
framework: jest
postMerge:
  env:
    NODE_OPTIONS: "--max-old-space-size=7000 --experimental-vm-modules --trace-deprecation"
  pattern:
    - 'test/*.unittest.js'
preMerge:
  env:
    NODE_OPTIONS: "--max-old-space-size=7000 --experimental-vm-modules --trace-deprecation"
  pattern:
    - 'test/*.unittest.js'
preRun:
  env:
    NODE_OPTIONS: "--max-old-space-size=7000 --experimental-vm-modules --trace-deprecation"
  command:
    - yarn run setup
    - env
postRun:
  command:
    - node --version
tier: medium
version: 2.0
