---
framework: jest
postMerge:
  pattern:
    - 'test/*.unittest.js'
preMerge:
  pattern:
    - 'test/*.unittest.js'
preRun:
  command:
    - yarn run setup
postRun:
  command:
    - node --version
tier: medium
version: 2.0
